### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by oojacoboo** [shustrik/vscode-symfony-plugin#3]
So, I've installed the plugin using the VSIX file.  It's installed and shows in my installed extensions.  It's also enabled.

Firstly, there aren't any errors.  Also, I don't see any configs.  Does this plugin assume the location of the `config.yml`?

**Comment by shustrik** [comment]
@oojacoboo This plugin doesn't have any configuration files. Plugin parses all xml and yaml files and tries to find service description. Log writes to "Symfony completion server" in "Output" tab. Example's on  the screenshot: 
![screenshot](https://user-images.githubusercontent.com/1706297/33518526-676956ca-d7a7-11e7-95ec-9c78d7771b0c.png)
 Also i can try to create some public symfony project and we can test on it.

**Comment by oojacoboo** [comment]
I don't have a `Symfony completion Server` available there.  What starts the server?

**Comment by shustrik** [comment]
@oojacoboo  extension client start server when you open php file. Try to open php file and if you don't see `Symfony completion Server` i'll add some log information

**Comment by oojacoboo** [comment]
@shustrik I tried to translate what you meant into something actionable, but I really have no clue what you mean by `extension client start server`.  Can you please elaborate.

**Comment by oojacoboo** [comment]
So, just checked the output console again and it appears to be showing up now.  I'm not sure why it wasn't showing earlier...  Here are the issues I'm showing:

```
[Info  - 18:09:51] Parse files start: yaml
[Info  - 18:09:51] Parse files start: xml
{ [Error: Unable to parse.]
  message: 'Unable to parse.',
  parsedLine: 30,
  snippet: 'if [ $TRAVIS_PHP_VERSION = \'5.6\' ]; then php vendor/bin/coveralls; fi' }
error parse yaml:/Volumes/repos/xxx/web/app/vendor/nikic/php-parser/.travis.yml
TypeError: argument.includes is not a function
    at createArgument (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:99:18)
    at parseArguments (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:84:30)
    at parseServices (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:55:40)
    at Object.parse (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:12:34)
    at parseRequestFile (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:111:21)
    at connection.onRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:44:5)
    at handleRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:354:27)
    at processMessageQueue (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:245:17)
    at Immediate.<anonymous> (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
error parse yaml:/Volumes/repos/xxx/web/app/src/xxx/Bridge/Entity/Persister.yml
TypeError: argument.includes is not a function
    at createArgument (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:99:18)
    at parseArguments (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:84:30)
    at parseServices (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:55:40)
    at Object.parse (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:12:34)
    at parseRequestFile (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:111:21)
    at connection.onRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:44:5)
    at handleRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:354:27)
    at processMessageQueue (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:245:17)
    at Immediate.<anonymous> (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
error parse yaml:/Volumes/repos/xxx/web/app/src/xxx/Adapter/Cache/Bank.yml
TypeError: argument.includes is not a function
    at createArgument (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:99:18)
    at parseArguments (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:84:30)
    at parseServices (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:55:40)
    at Object.parse (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:12:34)
    at parseRequestFile (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:111:21)
    at connection.onRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:44:5)
    at handleRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:354:27)
    at processMessageQueue (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:245:17)
    at Immediate.<anonymous> (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
error parse yaml:/Volumes/repos/xxx/web/app/src/xxx/Cog/Aws/S3Client.yml
[Info  - 18:09:52] Parse files start: php
{ [Error: Unable to parse.]
  message: 'Unable to parse.',
  parsedLine: 30,
  snippet: 'if [ $TRAVIS_PHP_VERSION = \'5.6\' ]; then php vendor/bin/coveralls; fi' }
error parse yaml:/Volumes/repos/xxx/coding-standard/vendor/nikic/php-parser/.travis.yml
TypeError: argument.includes is not a function
    at createArgument (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:99:18)
    at parseArguments (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:84:30)
    at parseServices (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:55:40)
    at Object.parse (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:12:34)
    at parseRequestFile (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:111:21)
    at connection.onRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:44:5)
    at handleRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:354:27)
    at processMessageQueue (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:245:17)
    at Immediate.<anonymous> (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
error parse yaml:/Volumes/repos/xxx/web/app/src/xxx/Cog/User/Password/Rule/MinimumLength.yml
TypeError: argument.includes is not a function
    at createArgument (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:99:18)
    at parseArguments (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:84:30)
    at parseServices (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:55:40)
    at Object.parse (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/services/parse/yamlParser.js:12:34)
    at parseRequestFile (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:111:21)
    at connection.onRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:44:5)
    at handleRequest (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:354:27)
    at processMessageQueue (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:245:17)
    at Immediate.<anonymous> (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
error parse yaml:/Volumes/repos/xxx/web/app/src/xxx/Cog/User/Username/Rule/MinimumLength.yml
[Info  - 18:09:54] Workspace files discovery ended: yaml | 444/444 files | 3.106 seconds
[Info  - 18:09:55] Workspace files discovery ended: xml | 578/578 files | 3.498 seconds
[Info  - 18:10:22] Workspace files discovery ended: php | 9872/9872 files | 30.476 seconds
TypeError: Cannot read property 'getVariable' of null
    at isServiceConditions (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:110:28)
    at /Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:12:50
    at walkAST (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:190:18)
    at walkAST (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:185:16)
    at walkAST (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:207:26)
    at Object.isService (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/php/completionHelper.js:12:9)
    at CompletionProvider.provideCompletionPHPItems (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/completion.js:17:20)
    at waitHandler (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:56:35)
    at waitHandler (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:120:18)
    at connection.onCompletion (/Users/jacob/.vscode/extensions/shustrik.vscode-symfony-client-0.1.1/server/server.js:51:12)
```

**Comment by shustrik** [comment]
Sorry for the late reply. I'll try to fix this issue next week. But anyway the autocomplete will work with files which were parsed without errors.

**Comment by shustrik** [comment]
I fix some parse problems. Now you can see only .travis.yml parse exceptions.
@oojacoboo  did you try to use autocomplete?
